name: second workflow test
on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: Print
        run: echo "Hello from runner"
      - name: list 
        run: ls 
      - name: Read file
        run: |
            cat README.md
            cat second-action.yml