name: Useing repository secret and repository environment variable
on: workflow_dispatch

env:
    docker_registry: docker.io
    docker_image: github-actions-nginx

jobs:
    Docker_build:
        runs-on: ubuntu-latest
        steps:
            - name: Build image
              run: echo docker build . -t ${{ env.docker_registry }}/${{ vars.docker_username }}/${{ env.docker_image }}:latest
            
            - name: Docker login
              run: echo docker login --username=${{ vars.docker_username }} --password=${{ secrets.docker_password }}

            - name: Publish image into Docker registry
              run: echo docker push ${{ env.docker_registry }}/${{ vars.docker_username }}/${{ env.docker_image }}:latest

    Deploy_Container:
        needs: Docker_build
        runs-on: ubuntu-latest
        steps:
            - name: Pull image
              run: echo docker pull ${{ env.docker_registry }}/${{ vars.docker_username }}/${{ env.docker_image }}:latest
            
            - name: Run the container
              run: echo docker run -d -p 8080:80 ${{ env.docker_registry }}/${{ vars.docker_username }}/${{ env.docker_image }}:latest